baseURL = "https://hetco.io/wgmlenses/"
languageCode = "en-us"
title = "WGM Visual"

[menu]
  [[menu.main]]
    name = "menu1"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "menu2"
    url = "/menu2/"
    weight = 2
  [[menu.main]]
    name = "menu3"
    url = "/menu3/"
    weight = 3